# Generated by Django 3.1.3 on 2020-11-19 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog1',
            name='Age',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='blog1',
            name='Name',
            field=models.CharField(max_length=200),
        ),
    ]
